name: ci

on:
  push:
    branches:
      - dev
      - master

env:
  DOCKER_LOGIN_NAME: ${{ secrets.DOCKER_LOGIN_NAME }}
  DOCKER_LOGIN_PASS: ${{ secrets.DOCKER_LOGIN_PASS }}
  DOCKER_HUB: "registry.cn-hangzhou.aliyuncs.com"
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: login aliyun docker hub
        run: echo "${{ env.DOCKER_LOGIN_PASS }}" | docker login "${{ env.DOCKER_HUB }}" -u "${{ env.DOCKER_LOGIN_NAME }}" --password-stdin
      - name: build
        run: docker build -t registry.cn-hangzhou.aliyuncs.com/ithrael123/k8sclient:v1.16.9 -f Dockerfile .
      - name: push
        run: docker push registry.cn-hangzhou.aliyuncs.com/ithrael123/k8sclient:v1.16.9